/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'executionLog': MotiaStream<{ id: string; executionId: string; step: string; stepType: string; phase: 'start' | 'data' | 'result' | 'error' | 'end'; message: string; payload?: unknown; timestamp: number }>
  }

  interface Handlers {
    'workflow.start': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'workflow.run': EventHandler<never, { topic: 'input'; data: never } | { topic: 'dbFind'; data: never } | { topic: 'dbInsert'; data: never } | { topic: 'dbUpdate'; data: never } | { topic: 'delay'; data: never } | { topic: 'authMiddleware'; data: never } | { topic: 'emailSend'; data: never } | { topic: 'inputValidation'; data: never }>
    'getWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'workflowMutation': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'saveWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'runWorkflowPublic': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'inputValidation': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'input': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'getDbSchemas': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'generateWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'explainWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ExecutionLogs': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'executeWorkflow': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'workflow.start'; data: never }>
    'emailSend': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'delay': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'dbUpdate': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'dbInsert': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'dbFind': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'authMiddleware': EventHandler<never, { topic: 'workflow.run'; data: never }>
    'aiIntent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}